version: '3.7'

services:
  app:
    build:
      context: ./build
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    env_file:
      - ./configs/.env
  db:
    image: postgres
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    hostname: ${DB_HOST}

  test_db:
    image: postgres
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TEST_NAME: ${DB_TEST_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    hostname: ${DB_HOST}
